'use client';

import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';

export default function PreferencesPage() {
  const [preferences, setPreferences] = useState({
    secondBrain: true,
    emailNotifications: false,
    autoGenerateDrafts: true,
    defaultReportFormat: 'pdf',
  });

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Preferences</h1>
        <p className="text-gray-600">Customize your Northstar experience</p>
      </div>

      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Chat Preferences</h3>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <Label htmlFor="second-brain">
                Enable Second Brain by default
              </Label>
              <p className="text-sm text-gray-600">
                Use knowledge bank for all chat queries
              </p>
            </div>
            <Switch
              id="second-brain"
              checked={preferences.secondBrain}
              onCheckedChange={(checked) =>
                setPreferences({ ...preferences, secondBrain: checked })
              }
            />
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Email Preferences</h3>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <Label htmlFor="email-notifications">Email notifications</Label>
              <p className="text-sm text-gray-600">
                Get notified when new drafts are ready
              </p>
            </div>
            <Switch
              id="email-notifications"
              checked={preferences.emailNotifications}
              onCheckedChange={(checked) =>
                setPreferences({ ...preferences, emailNotifications: checked })
              }
            />
          </div>

          <div className="flex items-center justify-between">
            <div>
              <Label htmlFor="auto-drafts">Auto-generate drafts</Label>
              <p className="text-sm text-gray-600">
                Automatically create drafts for incoming emails
              </p>
            </div>
            <Switch
              id="auto-drafts"
              checked={preferences.autoGenerateDrafts}
              onCheckedChange={(checked) =>
                setPreferences({ ...preferences, autoGenerateDrafts: checked })
              }
            />
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Report Preferences</h3>
        <div className="space-y-4">
          <div>
            <Label htmlFor="default-format">Default report format</Label>
            <Select
              value={preferences.defaultReportFormat}
              onValueChange={(value) =>
                setPreferences({ ...preferences, defaultReportFormat: value })
              }
            >
              <SelectTrigger className="w-full mt-2">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="pdf">PDF</SelectItem>
                <SelectItem value="powerpoint">PowerPoint</SelectItem>
                <SelectItem value="word">Word</SelectItem>
                <SelectItem value="google_slides">Google Slides</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </Card>

      <Button disabled>Save Preferences (Coming Soon)</Button>
    </div>
  );
}
